services:
  docs:
    image: farm_buddies_local_docs
    container_name: farm_buddies_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./farm_buddies:/app/farm_buddies:z
    ports:
      - '9000:9000'
    command: /start-docs
