# Generated by Django 4.1.13 on 2024-06-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                ("name", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        max_length=320, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "age",
                    models.CharField(
                        choices=[
                            (" <17", " <17"),
                            ("18-25", "18-25"),
                            ("26-30", "26-30"),
                            ("31-40", "31-40"),
                            ("41< ", "41< "),
                        ],
                        default="18-25",
                        max_length=100,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Female", "Female"), ("Male", "Male")],
                        default="Female",
                        max_length=100,
                    ),
                ),
                (
                    "governorate",
                    models.CharField(
                        choices=[
                            ("Alexandria", "Alexandria"),
                            ("Aswan", "Aswan"),
                            ("Asyut", "Asyut"),
                            ("Beheira", "Beheira"),
                            ("Beni Suef", "Beni Suef"),
                            ("Cairo", "Cairo"),
                            ("Dakahlia", "Dakahlia"),
                            ("Damietta", "Damietta"),
                            ("Faiyum", "Faiyum"),
                            ("Gharbia", "Gharbia"),
                            ("Ismailia", "Ismailia"),
                            ("Kafr El Sheikh", "Kafr El Sheikh"),
                            ("Matrouh", "Matrouh"),
                            ("Minya", "Minya"),
                            ("Monufia", "Monufia"),
                            ("Al Wadi al Jadid", "Al Wadi al Jadid"),
                            ("North Sinai", "North Sinai"),
                            ("Port Said", "Port Said"),
                            ("Qalyubia", "Qalyubia"),
                            ("Red Sea", "Red Sea"),
                            ("Sharqia", "Sharqia"),
                            ("Sohag", "Sohag"),
                            ("South Sinai ", "South Sinai "),
                            ("Suez", "Suez"),
                        ],
                        default="Alexandria",
                        max_length=100,
                    ),
                ),
                (
                    "cs_field",
                    models.CharField(
                        choices=[
                            ("UI/UX", "UI/UX"),
                            ("Front-End (React.js)", "Front-End (React.js)"),
                            ("Front-End (Angular)", "Front-End (Angular)"),
                            ("Back-End (Python)", "Back-End (Python)"),
                            ("Back-End (PHP)", "Back-End (PHP)"),
                            ("Back-End (Java)", "Back-End (Java)"),
                            ("MEAN", "MEAN"),
                            ("MERN", "MERN"),
                            ("DevOps", "DevOps"),
                            ("Artificial Intelligence", "Artificial Intelligence"),
                            ("Machine Learning", "Machine Learning"),
                            ("Robotics", "Robotics"),
                            ("Data Science", "Data Science"),
                            ("Cybersecurity", "Cybersecurity"),
                            ("Cloud Computing", "Cloud Computing"),
                            ("IoT", "IoT"),
                            ("Networks", "Networks"),
                            ("Game Development", "Game Development"),
                            ("Embedded Systems", "Embedded Systems"),
                            ("Bioinformatics", "Bioinformatics"),
                        ],
                        default="UI/UX",
                        max_length=100,
                    ),
                ),
                (
                    "experience_levels",
                    models.CharField(
                        choices=[
                            ("Entry-Level", "Entry-Level"),
                            ("Junior", "Junior"),
                            ("Mid-Level ", "Mid-Level "),
                            ("Senior", "Senior"),
                            ("Lead", "Lead"),
                        ],
                        default="Junior",
                        max_length=100,
                    ),
                ),
                ("twitter_link", models.URLField(max_length=500)),
                ("github_link", models.URLField(max_length=500)),
                (
                    "buddy_age",
                    models.CharField(
                        choices=[
                            ("Any", "Any"),
                            (" <17", " <17"),
                            ("18-25", "18-25"),
                            ("26-30", "26-30"),
                            ("31-40", "31-40"),
                            ("41< ", "41< "),
                        ],
                        default="18-25",
                        max_length=100,
                    ),
                ),
                (
                    "buddy_gender",
                    models.CharField(
                        choices=[
                            ("Any", "Any"),
                            ("Female", "Female"),
                            ("Male", "Male"),
                        ],
                        default="Female",
                        max_length=100,
                    ),
                ),
                (
                    "buddy_governorate",
                    models.CharField(
                        choices=[
                            ("Any", "Any"),
                            ("Alexandria", "Alexandria"),
                            ("Aswan", "Aswan"),
                            ("Asyut", "Asyut"),
                            ("Beheira", "Beheira"),
                            ("Beni Suef", "Beni Suef"),
                            ("Cairo", "Cairo"),
                            ("Dakahlia", "Dakahlia"),
                            ("Damietta", "Damietta"),
                            ("Faiyum", "Faiyum"),
                            ("Gharbia", "Gharbia"),
                            ("Ismailia", "Ismailia"),
                            ("Kafr El Sheikh", "Kafr El Sheikh"),
                            ("Matrouh", "Matrouh"),
                            ("Minya", "Minya"),
                            ("Monufia", "Monufia"),
                            ("Al Wadi al Jadid", "Al Wadi al Jadid"),
                            ("North Sinai", "North Sinai"),
                            ("Port Said", "Port Said"),
                            ("Qalyubia", "Qalyubia"),
                            ("Red Sea", "Red Sea"),
                            ("Sharqia", "Sharqia"),
                            ("Sohag", "Sohag"),
                            ("South Sinai ", "South Sinai "),
                            ("Suez", "Suez"),
                        ],
                        default="Alexandria",
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
